version: 2.1
jobs:
  compile:
   docker:
      - image: fr3akyphantom/droid-builder:latest
   steps:
      - run:
          command: |
            git clone https://github.com/ganomin/ci-twrp-deen-files ~/TWRP-9
            cd ~/TWRP-9 && bash build-twrp-circleci.sh
      - store_artifacts:
          path: ~/final/ 
workflows:
  version: 2.1
  cooking:
    jobs:
      - compile